jobs:
  - job: Test
    pool:
      vmImage: 'Ubuntu 16.04'
    variables:
      NODE_VERSION: 12.16.1
      SPRING_OUTPUT_ANSI_ENABLED: NEVER
      SPRING_JPA_SHOW_SQL: false
      JHI_DISABLE_WEBPACK_LOGS: true
      NG_CLI_ANALYTICS: 'false'

    steps:
      #----------------------------------------------------------------------
      # Install all tools and check configuration
      #----------------------------------------------------------------------
      - task: NodeTool@0
        inputs:
          versionSpec: $(NODE_VERSION)
        displayName: 'TOOLS: install Node.js'
      #----------------------------------------------------------------------
      # Tests
      #----------------------------------------------------------------------
      - task: Npm@1
        inputs:
          command: 'install'
        displayName: 'INSTALL: launch npm install'
      - script: |
          chmod +x mvnw
          ./mvnw -ntp checkstyle:check
          ./mvnw -ntp clean verify -P-webpack
        displayName: 'TESTS: backend'
      - task: Npm@1
        inputs:
          command: 'custom'
          customCommand: 'run test-ci'
        displayName: 'TESTS: frontend'
      - script: ./mvnw -ntp verify -Pprod -DskipTests
        displayName: 'TESTS: packaging'
