version: '2'
services:
  jhipsterdenemeuygulama-app:
    image: jhipsterdenemeuygulama
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:sqlserver://jhipsterdenemeuygulama-mssql:1433;database=jhipsterdenemeuygulama
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
      - SPRING_DATA_JEST_URI=http://jhipsterdenemeuygulama-elasticsearch:9200
      - SPRING_ELASTICSEARCH_REST_URIS=http://jhipsterdenemeuygulama-elasticsearch:9200
    ports:
      - 8080:8080
  jhipsterdenemeuygulama-mssql:
    extends:
      file: mssql.yml
      service: jhipsterdenemeuygulama-mssql
  jhipsterdenemeuygulama-elasticsearch:
    extends:
      file: elasticsearch.yml
      service: jhipsterdenemeuygulama-elasticsearch
